Created a rough draft of Profile Page
hack4impact-uiuc/roomble pull request #15
Opened 2020-11-20 00:28 UTC by nkonjeti

2020-11-20 04:55 UTC, coconut750750 commented
Looks pretty good

2020-12-02 04:32 UTC, alicesf2 reviewed
Looks good :nehalapeno:! I'll wait until you finish the edit profile page to approve

2020-12-02 04:32 UTC, alicesf2 commented on frontend/src/pages/Profile.js
> +  const data = await loadProfile("5fadf6bba3e3324e794a1141");
I would suggest changing the variable name to something more specific, like profile

2020-12-02 04:32 UTC, alicesf2 commented on frontend/src/styles/Profile.css
> +.profile-mediaIcons {
good use of css classes :D

2020-12-02 04:32 UTC, alicesf2 commented on backend/index.js
> +app.get('/profilepage/:userid', async (req, res) => {
nitpick: try to camelcase all javascript variables (i.e. userid -> userId)

2020-12-02 04:32 UTC, alicesf2 commented on frontend/src/utils/api.js
> +export async function loadProfile(userid) {
change this to userId too

2020-12-06 03:20 UTC, coconut750750 requested changes

2020-12-06 03:20 UTC, coconut750750 commented on backend/index.js
> +//const Pusheens = require("./models/Pusheens.js");
get rid of some of these comments

2020-12-06 03:22 UTC, nkonjeti commented on backend/index.js
> +//const Pusheens = require("./models/Pusheens.js");
👍🏽

2020-12-06 03:39 UTC, coconut750750 approved these changes

2020-12-06 03:39 UTC, merged