Vc/submit profile info
hack4impact-uiuc/roomble pull request #16
Opened 2020-11-20 01:13 UTC by vasuchal

Form for users to create profiles and sign up

2020-11-20 03:39 UTC, alicesf2 commented on frontend/src/pages/SignupPage.js
> +const languageOptions = [
replace with real data eventually

2020-11-20 03:40 UTC, alicesf2 commented on frontend/src/pages/SignupPage.js
> +]
this one as well

2020-11-20 03:40 UTC, alicesf2 commented on frontend/src/pages/SignupPage.js
> +  const contentAlign = {display:"flex", justifyContent:"center"}
move styles to css file

2020-11-20 03:41 UTC, alicesf2 commented on frontend/src/styles/Signup.css
> +}
remove quotes around values

2020-11-20 03:44 UTC, alicesf2 approved these changes
Great job! The form looks good, just some minor code and file changes.

2020-12-02 02:56 UTC, coconut750750 requested changes, later dismissed

2020-12-02 02:56 UTC, coconut750750 commented on frontend/src/index.js
> +        <Route exact path="/signuppage" render={(props) => <SignupPage {...props} />} />
Just a small nit, but set `path="/signup"`

2020-12-02 02:56 UTC, coconut750750 commented on frontend/src/utils/api.js
> +export async function makePost(name, school, year, age, gender, major, phoneNumber, fbUsername, igUsername, scUsername, email, housingType, numRoommates, shortDesc, longDesc, quizAnswers) {
Change this function name to something more descriptive like `submitProfile`

2020-12-02 04:15 UTC, alicesf2 reviewed
Invalid data gets submitted to database upon correct submission, me & brandon will look into this

2020-12-06 03:29 UTC, alicesf2 approved these changes

2020-12-06 03:29 UTC, coconut750750 approved these changes

2020-12-06 03:30 UTC, merged